### ISSUE TITLE
Option to permute symbols in all layers

### ISSUE THREAD

**Issue by nimr0d** [dariogoetz/keyboard_layout_optimizer#45]
My understanding is that currently there is only an option to permute symbols in the base layer, and specifying which layers move with the base layer.

I would like to be able to permute symbols in all layers, and specifying which layers change with the base layer (for capital letters in particular).

Does this option exist?

**Comment by dariogoetz** [comment]
Such an option does not exist. The only options are "stay as is" and "move with the base layer".
One would need to find a way to easily describe the possible permutations allowed. Shall all symbols stay in their respective layers or would they be allowed to move between them? In the current situation, it is quite easy to describe a "complete" layout by simply providing a couple of base-layer symbols. How would such a description look like in the "free permutation" case?

**Comment by hpgisler** [comment]
I am a bit late to the topic, sorry, for that..

I am expermimenting with a 18-key keyboard (inspired by ben vallack), which provides 9 keys to each hand: 7 for index, middle, ring and pinky and 2 for the thumb.

Thus per layer, typically, there are 2 * 7 = 14 symbols available; so the alphas (lowercase) are distributed over two layers (layer switching occurs via a thumb key) . To optimize this layout, it would be necessary for the optimizer to work across the the 2 layers - i.e. also moving symbols from one layer to the other, if necessary.

Can this be achieved somehow with the current state of software?

**Comment by dariogoetz** [comment]
That's an interesting use case. 

With the current state of the software this is not possible. This is mainly due to the idea that one only provides only the first layer when specifying a layout. The other keys follow from the configured "base layout". 

I have an idea how such a thing could be done, if one does not consider all the configured base layout keys, but specifies all relevant symbols directly.

I'll see, if I can find some time to look into this.

**Comment by hpgisler** [comment]
that would be great - of course.

I am not fluent in rust (more more a C / C++ guy); however if I may be of any assistance, then please let me know.

**Comment by dariogoetz** [comment]
How does the keyboard look like? Two keys for each of index, middle, und Ring finger and one for the pinky?
```
  I M R
  I M R P
T T
```

**Comment by hpgisler** [comment]
yes

**Comment by dariogoetz** [comment]
I have added a new layout generator in the `layout_generator_branch`. It can be activated on the command-line using the option `--grouped-layout-generator`.

With this option, the given layout string can contain symbols for more than one layer. There is a new configuration field `grouped_layers` in the keyboard config that defines how many consecutive layers in the `base_layout` shall be grouped and then move together when specifying a layout. If, for instance, `grouped_layers: 2` and a key in the `base_layout` is `["a", "A", "b", "B"]`, then the `A` always moves together with the `a` and the `B` always moves together with the `b`. If in that case would be `grouped_layers: 3`, both `A` and `b` would move with `a`.

When giving the layout string on the command-line, you may specify every n-th symbol in the `base_layout` key lists, where n is the value of `grouped_layers`. In the above example, you could specify `a` and `b` (and `a` and `B` in the case of `grouped_layers: 3`.

There is an example keyboard config file called `config/keyboard/hgi.yml` that contains your keyboard that is pre-populated with the symbols for the alphabet in lowercase and uppercase. If you need symbol layers, you can add them as well. Keep in mind, though, that they, too, are then grouped based on `grouped_layers`.

During evaluation and optimization, only the first layers are shown. To view the others, please use the `plot` binary, e.g.
```
cargo run --release --bin plot -- "ldghuoistrneacvmwf,zqjkpb.xy" -l config/keyboard/hgi.yml --grouped-layout-generator
```
You can evaluate a layout with
```
cargo run --release -- "ldghuoistrneacvmwf,zqjkpb.xy" --grouped-layout-generator -l config/keyboard/hgi.yml -n ngrams/eng_web_1m
```

For optimization with simulated annealing, you may use
```
cargo run --release --bin optimize_sa -- --run-forever --init-temp 10 --fix-from "ldghuoistrneacvmwf,zqjkpb.xy" --grouped-layout-generator -l config/keyboard/hgi.yml -n ngrams/eng_web_1m
```
for a genetic optimization:
```
cargo run --release --bin optimize_genetic -- -s "bcgj,.rnsteaihvfkzqxwpdluoym" --grouped-layout-generator -l config/keyboard/hgi.yml -n ngrams/eng_web_1m
```

**Comment by dariogoetz** [comment]
I came up with this layout after some initial optimization:
```
Layer 1:
        ┌───┐                         ┌───┐
    ┌───┤ c ├───┐                 ┌───┤ , ├───┐
    │ b ├───┤ g │                 │ j ├───┤ . │
    ├───┤ s ├───┤                 ├─━─┤ a ├───┤
┌───┤ n ├───┤ t │                 │ e ├───┤ i ├───┐
│ r ├───┘   └───┘                 └───┘   └───┤ h │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘
Layer 2:
        ┌───┐                         ┌───┐
    ┌───┤ f ├───┐                 ┌───┤ q ├───┐
    │ v ├───┤ k │                 │ z ├───┤ x │
    ├───┤ d ├───┤                 ├─━─┤ o ├───┤
┌───┤ p ├───┤ l │                 │ u ├───┤ y ├───┐
│ w ├───┘   └───┘                 └───┘   └───┤ m │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘
```

**Comment by hpgisler** [comment]
Wow, this is great, thank you!

I am experimenting with that right now. (I am using `ngrams/deu_mixed_wiki_web_0.6_eng_news_typical_wiki_web_0.4`, as my usual typed language is a german / english mix).

How am I supposed to specify the additional cost for accessing layer 3 (by pre-pending '⇙') with right thumb key - if possible?
I.e. in your found layout from above, typing `u` obviously costs more than `⇙e`.

However, the found solutions seem good.

How do you usually operate: Is your found solution from above the direct result of an optimization (i.e. sa or genetic?) or do you also manually 'tweak' such a one? (probably not feasible, is it?)

I had a minor problem while building the whole project with 
`cargo build --release` (after `cargo clean --release`) which affects obviously only `layout_optimization_abc` - which I am not using here; anyways, I get the following error:
```
   Compiling keyboard_layout_optimizer v0.1.0 (/home/hp/loc/keyboard_layout_optimizer/keyboard_layout_op
error[E0432]: unresolved import `layout_optimization_abc`
 --> keyboard_layout_optimizer/src/bin/optimize_abc.rs:3:5
  |
3 | use layout_optimization_abc::optimization;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `layout_optimization_abc`
  |
help: there is a crate or module with a similar name
  |
3 | use layout_optimization_sa::optimization;
  |     ~~~~~~~~~~~~~~~~~~~~~~

error[E0277]: the trait bound `Box<dyn LayoutGenerator>: LayoutGenerator` is not satisfied
  --> keyboard_layout_optimizer/src/bin/optimize_abc.rs:53:54
   |
53 |     let layout_generator: Box<dyn LayoutGenerator> = Box::new(layout_generator);
   |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `LayoutGe
   |
   = help: the following other types implement trait `LayoutGenerator`:
             GroupedLayoutGenerator
             NeoLayoutGenerator
   = note: required for the cast from `Box<dyn LayoutGenerator>` to the object type `dyn LayoutGenerator

Some errors have detailed explanations: E0277, E0432.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `keyboard_layout_optimizer` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by dariogoetz** [comment]
I forgot to check in deleting the `optimize_abc.rs` binary in `keyboard_layout_optimizer/src/bin`. Deleting it should fix the issue. The ABC algorithm was just an experiment and would have required some work to properly align to the changes, so I deleted it.

Giving an answer to your question regarding layer 3 is difficult per se and depends on the type of metric. 
Generally, higher layers only have additional cost, if the `split_modifiers` evaluation config parameter is enabled (which it is, by default).

The idea is that in order to generate a symbol on a higher layer (e.g. `u` in your example), that key press is split into the keypress of the base layer and keypresses for all configured modifiers for the corresponding layer (see the `modifiers` keyboard config parameter). An uppercase `U`, for instance, would be split into `e`, `shift`, and `⇙`.
For the `key_cost` metric this means that the cost for `U` is the same as the sum of costs of these three keys.

For bigram metrics, the situation is more complex as the order in which the various modifier keys are pressed is unclear. `ue` would be split into `ea`, `⇙e`, and `⇙a`. If the second symbol is on another layer also, there are more combinations. And if multiple modifiers are used, there are even more combinations. All these are evaluated and their metric costs are summed.

As you may guess, the situation can get somewhat crazy for Trigram metrics...

Anyway, that's the logic with which the costs for higher layer symbols increase. All this happens automatically. For the easiest `key_cost` metric, you just need to make sure that the key costs on the thumb keys have proper values. 

Now regarding your last question: If I seriously want to generate a layout that I can "believe in", I do the following:

I use the simulated annealing to start from scratch and let it run for a couple of hundred solutions (called processes in the logs, I believe). In the end, you get a nice high score table with the best solutions. A couple of score points more or less don't make a huge difference, so from the high scorers I choose a couple using my gut feeling and some "felt" preferences that I would not be able to put into words or numbers.

Then I play a little with the metric weights and config and let it run again. Every time I keep one or two nice layouts into a short list. I repeat the same procedure for other corpora.

Finally, I evaluate the short list on different corpora and try to pick one that I have the best feeling with. One can then also try to use the genetic optimization to see if there are some improvements that one missed. Sometimes I also do some manual changes that come out at a worse score but just "feel good" to me. Most of the time this is weighing "movement pattern" costs vs "finger repeat" costs. Or "finger balance". 

But to be honest, for the layout above (for the 18 key keyboard) I just let the simulated annealing run for some time and picked the first one ;)

**Comment by dariogoetz** [comment]
I wonder why the `j` came out on the base layer. It is really uncommon and to top it off, mostly paired with `u` and `o`  which are located on the other layer.

Maybe there is still something off somewhere...

**Comment by hpgisler** [comment]
I was also wondering about the `u`, `o` ending up on the 2nd layer, and the `,` and `.` ending up on the first layer...

For example, with `optimize_sa` I got the following layout:

```
Layout 'mlcj.,rsnteiahvpbqyxzfwdkuog' (layer 1):
        ┌───┐                         ┌───┐
    ┌───┤ l ├───┐                 ┌───┤ . ├───┐
    │ m ├───┤ c │                 │ j ├───┤ , │
    ├───┤ n ├───┤                 ├─━─┤ i ├───┤
┌───┤ s ├───┤ t │                 │ e ├───┤ a ├───┐
│ r ├───┘   └───┘                 └───┘   └───┤ h │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘

Layout 'mlcj.,rsnteiahvpbqyxzfwdkuog' (layer 2):
        ┌───┐                         ┌───┐
    ┌───┤ p ├───┐                 ┌───┤ y ├───┐
    │ v ├───┤ b │                 │ q ├───┤ x │
    ├───┤ w ├───┤                 ├─━─┤ u ├───┤
┌───┤ f ├───┤ d │                 │ k ├───┤ o ├───┐
│ z ├───┘   └───┘                 └───┘   └───┤ g │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘
```

(For simplicity, I've just let the optimizer do the 2 layers for lower case letters and with `grouped_layers: 1`)

For key-costs I did:

```
  key_costs:
    - [     5,  4,  7,                     7,  4,  5    ]
    - [ 6,  3,  2,  3,                     3,  2,  3,  6]
    - [                  5,  7,    7,  5                ]
```

So even with a relatively high right thumb-home-position value of 5, those four keys suspiciously remain on their respective layers...

Just in case you want to have a look in detail on my settings:
[My fork](https://github.com/hpgisler/keyboard_layout_optimizer/tree/layout_generator_trait)

**Comment by dariogoetz** [comment]
I think the reason is that currently, thumb usage is too cheap.

Thumb usage is considered in the `key_cost` metric, the `finger_repeats` metric (which basically only accounts for space-modifier combinations), and, I believe, in the `secondary_bigrams` metric (but then indirectly mostly if the second symbol is used by the thumb).

In particular, the movement pattern metric, which would account for the largest amount of bigrams, excludes the thumb.

This means that the thumb only plays a minor role in bigram and Trigram costs. Therefore, the decision on which layer one places a key is mostly accounted for in the `key_cost` metric, which only makes a small part of the overall cost. Historically, this was no issue because every symbol hat it's fixed layer where it belonged. 

I think, we should change the `movement_pattern` metric to also consider the thumb. This would cover the bigrams on the right hand. Movement patterns with a hand change have no cost. Generally, most of the metrics consider hand switches as "for free", which, however, is good in the usual case... 

This is different, however, when one needs to hold a key. Holding a key on one hand and then typing a key on the other hand is more "complex" than just typing with a hand switch, I believe. Maybe there should also be cost associated to every (hold) modifier usage apart from the other metrics.

**Comment by hpgisler** [comment]
Ok, I believe I start to understand what you mean..

Is the `movement_pattern` metric relevant for any n-gram (i.e.. also for example for `secondary_bigrams`) of the same hand or only for bigrams? I.e. If I want to type `ye` (in above example keymap of mine), I would type `⇙`, then y (by typing `.`) then `e`; does this lead to 2 movement patterns on the right hand to be regarded, one for first bigram `⇙.` { from: [Right, Thumb], to: [Right, Ring],   cost: 0.1 } and one for second bigram `ye` { from: [Right, Ring], to: [Right, Index],   cost: 0.1 }? This would be precondition for the proposal to work, no?

However, this would not lead to different costs when hitting for example `⇙e` vs. `⇙j` because both are right-Thumb and right-Index finger combinations, yes? But the two bigrams 'feel' different when hit (at least to me). 

On the other hand `manual_bigram_penalty' metric would allow describing the precise matrix positions of bigram participating keys. By the way, could `manual_bigram_penalty` already be used to achieve the desired effect, by adding `[[13, 4], [<each key out of 14>]]: -0.01 # ⇙<each key out of 14>?

**Comment by dariogoetz** [comment]
The `movement_pattern` metric is a bigram-metric (immediately), i.e. it takes the bigrams as input. However, the two trigram-metrics `secondary_bigrams` and `irregularity` also employ the `movement_pattern` metric indirectly by generating "virtual" bigrams from each trigram and evaluating all bigram-metrics on these (the `secondary_bigrams` takes the first and last symbol of the trigram as bigram, the `irregularity` takes both the bigram of first and second symbols and second and third symbols as bigrams).

For your example, the bigram `ye`, would be "expanded" or "split" into `⇙.`, `⇙e` (because `⇙` is held even after `.` is released), and `.e`. The `movement_pattern` metric is evaluated for all three of them.

Now regarding the `movement_pattern` costs for `⇙e` vs. `⇙j`, the metric is more complex than just using the values for the `finger_switch_factors`, e.g. `{ from: [Right, Thumb], to: [Right, Index], cost: 0.1 }`. Also covered are the number of rows that lie between the keys, whether the movement is going from a longer finger "up" to a shorter finger (or the other way from a shorter finger "down" to a longer finger) - the latter does not make much sense for the thumb, though - and if one of the keys is "unbalancing", i.e. drawing the hand out of its "normal" position.

With the `manual_bigram_penalty`, you could also achieve something like that, yes. It is, however, quite tedious to configure ;)

**Comment by hpgisler** [comment]
Thank you for your as always very concise reply and explanation.

I've been experimenting a bit with the `manual_bigram_penalty` by defining the whole second layer that way (see below).
Additionally I've added `-f ",." and fixed them on the second layer like this:

`RUST_LOG=info cargo run --release --bin optimize_sa -- --run-forever --init-temp 10 --grouped-layout-generator -l config/keyboard/hgi.yml  -e config/evaluation/hgi.yml  -f ",." --fix-from
"cndoubsrlteihazwj,xyvfmg.qpk"`

What is still strange though - and what you already noted earlier is that `j` mostly (not always) sticks to the 1st layer...
Any ideas on that?

e.g.

```
Layout 'mldoujrnstaiehxwv,yqzbgc.kpf' (layer 1):
        ┌───┐                         ┌───┐
    ┌───┤ l ├───┐                 ┌───┤ u ├───┐
    │ m ├───┤ d │                 │ o ├───┤ j │
    ├───┤ s ├───┤                 ├─━─┤ i ├───┤
┌───┤ n ├───┤ t │                 │ a ├───┤ e ├───┐
│ r ├───┘   └───┘                 └───┘   └───┤ h │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘

Layout 'mldoujrnstaiehxwv,yqzbgc.kpf' (layer 2):
        ┌───┐                         ┌───┐
    ┌───┤ w ├───┐                 ┌───┤ y ├───┐
    │ x ├───┤ v │                 │ , ├───┤ q │
    ├───┤ g ├───┤                 ├─━─┤ k ├───┤
┌───┤ b ├───┤ c │                 │ . ├───┤ p ├───┐
│ z ├───┘   └───┘                 └───┘   └───┤ f │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ␣ │ ⇧ │ │ ⏎ │ ⇙ │
                └───┴───┘ └───┴───┘

Layout compact:
 mld ouj
rnst aieh
```
here my `manual_bigram_penalty` configuration section.
What I am unsure of however: how am I supposed to chose the factor: `weight: 5.0`
Is there some _best practice_ for this?

```
  # Put costs on some key combinations that are hard to describe otherwise
  manual_bigram_penalty:
    enabled: true
    weight: 5.0
    normalization:
      type: weight_found
      value: 1.0
    params:
      # if mirrored bigrams to the ones in "matrix_positions" below shall be added automatically
      add_mirrored: false

      # key positions as matrix positions and the corresponding costs
      # the format is [column, row]
      # [from_position, to_position]: weight
      matrix_positions:

      # hgi
      # [         [3,2]:5, [4,2]:4, [5,2]:7,     [14,2]:8, [15,2]:4, [16,2]:4          ]
      # [[2,3]:6, [3,3]:3, [4,3]:2, [5,3]:3,     [14,3]:9, [15,3]:5, [16,3]:3 ,[17,3]:4]

        [[13,4], [3,2]]: 5 
        [[13,4], [4,2]]: 4
        [[13,4], [5,2]]: 7

        [[13,4], [2,3]]: 6
        [[13,4], [3,3]]: 3
        [[13,4], [4,3]]: 2
        [[13,4], [5,3]]: 3


        [[13,4], [14,2]]: 8 
        [[13,4], [15,2]]: 4
        [[13,4], [16,2]]: 4

        [[13,4], [14,3]]: 9
        [[13,4], [15,3]]: 5
        [[13,4], [16,3]]: 3
        [[13,4], [17,3]]: 4
```

**Comment by hpgisler** [comment]
Thank you very much for your explanations.

Is the additional cost a modifier for reaching another layer (e.g. layer 1) always added for each key press on that layer 1 or can I configure it such, that it is counted once only if I can press e.g. a bigram or a trigram on layer 1?

E.g. in above layout, if wanted to write `g,` I would have to option of pressing either `⇙s⇙o` (releasing `⇙` after each keypress) or `⇙so` by holding `⇙` during the following two keypresses `so`, which would be cheaper than the first option.

**Comment by dariogoetz** [comment]
The new metric is a very simple one, only working on unigrams (called a `UnigramMetric`). So it simply counts modifiers for individual keys, not bigrams or trigrams.
In particular, this means that `g,` would count two modifiers instead of one.

To achieve the "cheaper" `⇙so`, the metric would need to be implemented as a `BigramMetric` (or even a `TrigramMetric`). Then the following would happen: The bigram `g,` would be expanded into 
- `so` - no modifier
- `⇙s` (shift from `g`) - counts one modifier
- `⇙o` (shift from `g`) - counts one modifier
- `s⇙` (shift from `,`) - counts one modifier
-  `⇙o` (shift from `,`) - counts one modifier
- `⇙⇙` (both shifts) - gets excluded automatically because it is a "long hold"
(note that `s⇙` with shift from `s` and `o⇙` with shift from `o` are intentionally not considered because the shift key is always pressed before the key that it shall modify).

Each of the bigrams "inherits" the weight (number of occurrences in the corpus) of the original bigram. So `g,` generates six bigrams out of which four count a modifier. Assuming the weight of `g,` is 1 and the new metric has a weight of one, this would give a metric cost of 4/5. The current unigram metric would count two modifiers for two unigrams, so 2/2=1.

`go` on the other hand would expand to `⇙s`, `⇙o`, `so`, out of which two are modifiers. So `go` would give metric cost 2/3. The current unigram metric would count one modifier out of two unigrams, so 1/2.

So the bigram metric counts higher than the unigram metric for "single-modifier" bigrams but lower than the unigram metric for "double-modifier" bigrams. I guess, that this is the behavior that you are aiming for.

Implementing such a bigram metric is actually not hard (even without much rust knowledge). You can find the general recipe in the readme. You can also look at the other modifier metric and the bigram metrics for guidance. If you have issues with the implementation, please write again here.

**Comment by zeitlinger** [comment]
Hi, what is your experience with this layout?

**Comment by dariogoetz** [comment]
I don't have any experience with this layout because I have 42 keys on my keyboard :)

I'm using [that one](https://github.com/dariogoetz/noted-layout) and I'm very happy with it.

**Comment by hpgisler** [comment]
> Hi, what is your experience with this layout?

My afore mentioned 18 key layout has evolved in the last couple of weeks. The main symbols locations are:

```
Layout 'nhduoarst eijkv/qöwzpc,yxmb'?älfg-.ü' (layer 1):
        ┌───┐                         ┌───┐
    ┌───┤ h ├───┐                 ┌───┤ o ├───┐
    │ n ├───┤ d │                 │ u ├───┤ a │
    ├───┤ s ├───┤                 ├───┤ e ├───┤
┌───┤ r ├───┤ t │                 │ ␣ ├───┤ i ├───┐
│ ⇧ ├───┘   └─━─┘                 └─━─┘   └───┤ ⇧ │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ⇘ │ ⇧ │ │ ⇧ │ ⇙ │
                └───┴───┘ └───┴───┘

Layout 'nhduoarst eijkv/qöwzpc,yxmb'?älfg-.ü' (layer 2):
        ┌───┐                         ┌───┐
    ┌───┤ k ├───┐                 ┌───┤ q ├───┐
    │ j ├───┤ v │                 │ / ├───┤ ö │
    ├───┤ z ├───┤                 ├───┤ , ├───┤
┌───┤ w ├───┤ p │                 │ c ├───┤ y ├───┐
│ ⇧ ├───┘   └─━─┘                 └─━─┘   └───┤ ⇧ │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ⇘ │ ⇧ │ │ ⇧ │ ⇙ │
                └───┴───┘ └───┴───┘

Layout 'nhduoarst eijkv/qöwzpc,yxmb'?älfg-.ü' (layer 3):
        ┌───┐                         ┌───┐
    ┌───┤ m ├───┐                 ┌───┤ ? ├───┐
    │ x ├───┤ b │                 │ ' ├───┤ ä │
    ├───┤ f ├───┤                 ├───┤ . ├───┤
┌───┤ l ├───┤ g │                 │ - ├───┤ ü ├───┐
│ ⇧ ├───┘   └─━─┘                 └─━─┘   └───┤ ⇧ │
└───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                │ ⇘ │ ⇧ │ │ ⇧ │ ⇙ │
                └───┴───┘ └───┴───┘
```

Note however, that there are a total of 11 layers, including digits, function keys, cursor movements, special symbols, wm controls, etc.

The 3 layers shown above are the result of the optimizer, with minor manual adaptions.
The corpus used for optimization is: `deu_mixed_wiki_web_0.6_eng_news_typical_wiki_web_0.4`

What I find most interesting ist the fact, that (for me) the 3 layers with only 12 netto symbols per layer work better than 2 layers with 14 netto symbols on them - regarding finger-key-ngram flow. With the 12 symbols approach, the pinkies are used exclusively for `SHIFT` (left pinky) and `CTRL/ESC` combo (right pinky). The home-row for left:ring-middle-index and right:index-middle-ring fingers is: `r` `s` `t`    `SPC` `e` `i`

The 2 inner thumb positions (home pos) are used for switching between the 3 layer shown above (and also between the not shown digits and braces layer - I am a programmer of sorts, you know..)

the outher thumbs then access the other, not so frequently used layers.

I am training this layout since about 2..3 weeks - I think - for a couple of minutes per day (not full time, as I am to slow during work time) and the current speed I get with it is slightly less than 20 wpm. Not great by all means, but there certainly is the potential to get faster on that.

**Comment by hpgisler** [comment]
Yes, mine was actually inspired by Ben Vallack. :-)
'final setup' ?

**Comment by zeitlinger** [comment]
Yes, do you want to share your final setup?

**Comment by hpgisler** [comment]
You can find my qmk setup here:
`https://github.com/hpgisler/qmk_firmware/tree/B6/keyboards/crkbd/keymaps/hpgisler`
