### ISSUE TITLE
Question about parsing of dash/hyphen/minus

### ISSUE THREAD

**Issue by conquerist** [dariogoetz/keyboard_layout_optimizer#76]
Using the online implementation at https://dariogoetz.github.io/keyboard_layout_optimizer/ I've run into a strange case when using "Ngrams from text" and having hyphens in there.

For example, with the text `a-b` as the custom text for the n-grams, the analysis results (with qwerty) show:

- `[⇩]` as unexpected unigram and `-` as "missing" unigram
- `a[⇩]` and `[⇩]b` as unexpected bigrams
- `a[⇩]b`, `a[⇩]l`, `[⇩]lb` and `alb` as unexpected trigrams

The `-` itself doesn't show up in the analysis results. Is there some special meaning to the minus/hyphen/dash symbol or are there some steps that are needed in order to have the `-` in the ngrams editor be treated as the symbol that's produced by hitting the `-` key on the keyboard?

[update]
and of course it's because the default config for ISO (`Standard`) has the `l` key loaded with `-` on one of the modifier layers 😅

**Comment by dariogoetz** [comment]
What you experienced is the combination of two effects:
1. The dash `-` appears (at least in the default config) at two different positions in the layout: On the base layer next to the 0 and on layer 3 on the home row, right ring finger (in the default config, all generated layouts belong to the "neo"-family and share their upper layers). When a symbol appears in separate places, the one with the least key costs (see "keyboard" config, section "key_costs") are taken. In this case it is 60 for the key next to the 0 on the base layer and 9+3 for the Mod3 modifier `⇩` plus the ring finger on the home row.
2. Symbols on higher layers (involving modifier keys) are resolved into their modifier usages before being analyzed. In particular, the `-` is split into `[⇩]` and `l` (I guess, you have QWERTY as layout, which means the third layer `-` is below the `l`) and does not appear itself anymore. This way, only "base-layer keys" are analyzed in the end. In the default case, the modifiers are configured as "hold" modifiers. So they are expected to be pressed before the "key to be modified" and released only after the "key to be modified" has been hit. This in particular means, that instead of only a bigram `al` you have multiple valid bigrams
    - `a[⇩]` (press the modifier before the modified key -> it follows after `a`, just like the 'l`)
    - `[⇩]l` (press the modifier before the modified key)
    - `[⇩]b` (hold the modifier as long as the modified key -> it will also be right before `b`, just like `l`)
    - ... and some more
 For trigrams, there are even more valid combinations.

Resolving higher layer keys into modifiers can be switched off by setting a config parameter `ngram_mapper`->`split_modifiers`->`enabled` in the `evaluation` config to `false`. Then, modifiers are not resolved, but then also ignored by most metrics.

**Comment by conquerist** [comment]
Thank you for getting back to me and for the detailed explanation. 
Please feel free to close!

PS: The "real solution" here is probably for me to start using additional layers (and... migrate away from QWERTY).
